---
- name: Common role
  hosts: all
  become: yes
  roles:
     - role: common
       when: ansible_os_family == "Debian"

- name: Build role
  hosts: build
  roles:
     - role: builder
       when:  ansible_os_family == "Debian"

- name: Production role
  hosts: prod
  roles:
     - role: prod
       when:  ansible_os_family == "Debian"
